### ISSUE TITLE
Gameplay report

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [JaroslawSlaby/OXTheGame#29]
Cannot validate data, o not accepted as character, only O, not enough message to user, can't put last char, no winner. Details, see session log

**Comment by LIttleAncientForestKami** [comment]
➜  target ±:(master) java -jar tictactoe-1.2-SNAPSHOT.jar                            [% 18:56:27]
Let's go!
Enter board size (All dimensions must be higher than 3) [pattern: x y]: 
3 3 
Enter 1st player name: 
33
Choose sign (O/X)
0
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.js.tictactoe.player.Sign.0
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.js.tictactoe.player.Sign.valueOf(Sign.java:3)
	at com.js.tictactoe.board.game.Game.createPlayers(Game.java:74)
	at com.js.tictactoe.board.game.Game.runGame(Game.java:36)
	at com.js.tictactoe.Main.main(Main.java:38)
➜  target ±:(master) java -jar tictactoe-1.2-SNAPSHOT.jar                            [% 18:57:35]
Let's go!
Enter board size (All dimensions must be higher than 3) [pattern: x y]: 
3 3
Enter 1st player name: 
1 
Choose sign (O/X)
o
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.js.tictactoe.player.Sign.o
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.js.tictactoe.player.Sign.valueOf(Sign.java:3)
	at com.js.tictactoe.board.game.Game.createPlayers(Game.java:74)
	at com.js.tictactoe.board.game.Game.runGame(Game.java:36)
	at com.js.tictactoe.Main.main(Main.java:38)
➜  target ±:(master) java -jar tictactoe-1.2-SNAPSHOT.jar                            [% 18:57:55]
Let's go!
Enter board size (All dimensions must be higher than 3) [pattern: x y]: 
3 3 
Enter 1st player name: 
1
Choose sign (O/X)
O
Enter 2st player name: 
aaa
|   ||   ||   |
|   ||   ||   |
|   ||   ||   |
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
3 3
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
2 2
|   ||   ||   |
|   ||   ||   |
|   ||   || O |
Player aaa make your move [pattern: x y] and x must be lower than 3, y lower than 3
2 1 
|   ||   ||   |
|   ||   ||   |
|   || X || O |
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
2 2
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
1 1
|   ||   ||   |
|   || O ||   |
|   || X || O |
Player aaa make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 1
|   || X ||   |
|   || O ||   |
|   || X || O |
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 0
| O || X ||   |
|   || O ||   |
|   || X || O |
Player aaa make your move [pattern: x y] and x must be lower than 3, y lower than 3
1 2
| O || X ||   |
|   || O || X |
|   || X || O |
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
2 1
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 1
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 2
| O || X || O |
|   || O || X |
|   || X || O |
Player aaa make your move [pattern: x y] and x must be lower than 3, y lower than 3
1 0
| O || X || O |
| X || O || X |
|   || X || O |
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
1 2
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 2
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 1
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
0 2
Player 1 make your move [pattern: x y] and x must be lower than 3, y lower than 3
^C%
