### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/OXTheGame#61]
```Language/Język/язык: PL/EN/RU: EN
java.io.FileNotFoundException: file:/home/boczkas/IdeaProjects/Jarek/OX/target/tictactoe-1.4.jar!/EN.lang (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at com.js.tictactoe.language.FileReader.setUpReaders(FileReader.java:35)
	at com.js.tictactoe.language.FileReader.loadString(FileReader.java:24)
	at com.js.tictactoe.game.configuration.Configuration.getInput(Configuration.java:59)
	at com.js.tictactoe.game.configuration.Configuration.createTable(Configuration.java:37)
	at com.js.tictactoe.game.Game.runGame(Game.java:34)
	at com.js.tictactoe.Main.main(Main.java:9)
May 16, 2018 10:29:30 AM com.js.tictactoe.language.FileReader loadString
WARNING: nullnull
null

**Comment by JaroslawZaczyk** [comment]
gotowe :)
