### ISSUE TITLE
Number format exception thrown

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/OXTheGame#68]
Enter number of signs to win:  [Space][Space][Space] 3

```
Enter number of signs to win:   3 
Exception in thread "main" java.lang.NumberFormatException: For input string: "  3 "
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.js.tictactoe.game.configuration.Configuration.getNumberOfSignsToWin(Configuration.java:107)
	at com.js.tictactoe.game.configuration.Configuration.chooseSequenceNumber(Configuration.java:92)
	at com.js.tictactoe.game.Game.runGame(Game.java:35)
	at com.js.tictactoe.Main.main(Main.java:9)

**Comment by JaroslawZaczyk** [comment]
done
